server:
  port: 80
  session:
    timeout: 2H
  tomcat:
    basedir: /root/violet/logs
    accesslog:
      pattern: '%t %m %s %v %U'
      enabled: true
      directory: visit-logs
      buffered: false

spring:
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 2000
        min-idle: 0
  cache:
    type: redis
    cache-name: redisCache

back:
  image-size: 9
  max-logins-counter: 10
  admin:
    name: pig
    password: 123456

front:
  article-size: 6

logging:
  config: logback-spring.xml

